<template>
  <div class="loader-content p-d-flex p-ai-center p-jc-center">
    <!--<img src="@/assets/wedges.gif" />-->
    <div class="loadingio-spinner-wedges-jw87czz7m19"><div class="ldio-y83t2c29fv">
    <div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div></div></div></div>
  </div>
</template>

<script>
export default {
  name: "Loader"
}
</script>

<style>
.loader-content {
  height: 100%;
  width: 100%;
}

.loadingio-spinner-wedges-jw87czz7m19 {
  width: 20%;
  max-width: 200px;
}


@keyframes ldio-y83t2c29fv {
  0% { transform: rotate(0deg) }
  100% { transform: rotate(360deg) }
}
.ldio-y83t2c29fv > div > div {
  transform-origin: 100px 100px;
  animation: ldio-y83t2c29fv 3.0303030303030303s linear infinite;
  opacity: 0.8
}
.ldio-y83t2c29fv > div > div > div {
  position: absolute;
  left: 0px;
  top: 0px;
  width: 100px;
  height: 100px;
  border-radius: 100px 0 0 0;
  transform-origin: 100px 100px
}.ldio-y83t2c29fv > div div:nth-child(1) {
  animation-duration: 0.7575757575757576s
}
.ldio-y83t2c29fv > div div:nth-child(1) > div {
  background: #3e6d8d;
  transform: rotate(0deg);
}.ldio-y83t2c29fv > div div:nth-child(2) {
  animation-duration: 1.0101010101010102s
}
.ldio-y83t2c29fv > div div:nth-child(2) > div {
  background: #4b9bbe;
  transform: rotate(0deg);
}.ldio-y83t2c29fv > div div:nth-child(3) {
  animation-duration: 1.5151515151515151s
}
.ldio-y83t2c29fv > div div:nth-child(3) > div {
  background: #eef3ef;
  transform: rotate(0deg);
}.ldio-y83t2c29fv > div div:nth-child(4) {
  animation-duration: 3.0303030303030303s
}
.ldio-y83t2c29fv > div div:nth-child(4) > div {
  background: #f9aa47;
  transform: rotate(0deg);
}
.loadingio-spinner-wedges-jw87czz7m19 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-y83t2c29fv {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-y83t2c29fv div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>